version: "3"
services:
  # 서비스명을 기본 호스트네임으로 잡는다. hostname: redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Redis의 기본 포트입니다.
    networks:
      - my-network
  app:
    image: "commerce" # 여기에 Spring Boot 도커 이미지 이름을 사용하세요.
    ports:
      - "8081:8081" # 호스트의 포트를 컨테이너의 포트에 매핑합니다.
    networks:
      - my-network
    volumes:
      # ----
      # 우분투 리눅스 볼륨위치
      # /var/lib/docker/volumes
      # 윈도우즈 볼륨위치
      # \\wsl$\docker-desktop-data\data\docker\volumes
      # ----
      - my-volume:/tmp
      # 먼저 실행되어야할 서비스(컨테이너) 목록
    depends_on:
      - redis
    # 서비스 실핼할 때 사용할 환경변수(컨테이너에서 사용할 변수)
    environment:
      - SPRING_PROFILES_ACTIVE=dev
# 네트워크 정의 영역
networks:
  my-network:
    driver: bridge
volumes:
  my-volume: